version: '3.8'
services: 
  gym-nest: 
    image: node:latest
    env_file:
      - ./.env
    container_name: gym-nest
    hostname: gym-nest
    ports:
      - ${DEV_APP_PORT}:${DEV_APP_PORT}
    working_dir: /usr/src/app
    volumes: 
      - ./:/usr/src/app    
    command: >
      sh -c "npm install &&
            npm run start:dev"
    depends_on:
      - gym-db
    networks:
      - gym
  gym-db:
    image: mysql:latest
    env_file:
      - ./.env
    container_name: gym-db
    hostname: gym-db
    ports:
      - ${DEV_DATABASE_PORT}:${DEV_DATABASE_PORT}
    environment:
      MYSQL_ROOT_PASSWORD: ${DEV_DATABASE_PWD}
      MYSQL_DATABASE: ${DEV_GYM_DATABASE_NAME}
      MYSQL_USERNAME: ${DEV_DATABASE_USER}
      MYSQL_PASSWORD: ${DEV_DATABASE_PWD}
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - gym
networks:
  gym:
    external: true 
    driver: bridge