version: '3.8'
services: 
  gym-nest: 
    image: node:latest
    env_file:
      - ./.env
    container_name: gym-nest
    hostname: gym-nest
    ports:
      - 3000:3000
    working_dir: /usr/src/app
    volumes: 
      - ./:/usr/src/app    
    command: >
      sh -c "npm install &&
            npm run start:dev"
    depends_on:
      - gym-db
    networks:
      - app
  gym-db:
    image: mysql:latest
    env_file:
      - ./.env
    container_name: gym-db
    hostname: gym-db
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PWD}
      MYSQL_DATABASE: ${GYM_DATABASE_NAME}
      MYSQL_USERNAME: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PWD}
    volumes:
      - ./database/:/docker-entrypoint-initdb.d
    restart: unless-stopped
    networks:
      - app
networks:
  app: 
    driver: bridge